
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2 (64-bit)
SW Build 928826 on Thu Jun  5 17:44:04 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_MDM_0_DEVICE_ID,
		XPAR_MDM_0_BASEADDR,
		XPAR_MDM_0_BAUDRATE,
		XPAR_MDM_0_USE_PARITY,
		XPAR_MDM_0_ODD_PARITY,
		XPAR_MDM_0_DATA_BITS
	}
};


