# TCL File Generated by Component Editor 11.1sp2
# Mon May 28 17:06:27 PDT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | vbvip_planar2is "vbvip_planar2is" v1.0
# | Wing-Chi Chow 2012.05.28.17:06:27
# | Converts planar video to Avalon stream
# | 
# | /nfs/home/wchow/project/vblox/ip/vbvip/vbvip_planar2is.vhd
# | 
# |    ./vbvip_planar2is.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module vbvip_planar2is
# | 
set_module_property DESCRIPTION "Converts planar video to Avalon stream"
set_module_property NAME vbvip_planar2is
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Video and Image Processing/Component Library"
set_module_property AUTHOR "Wing-Chi Chow"
set_module_property DISPLAY_NAME vbvip_planar2is
set_module_property TOP_LEVEL_HDL_FILE vbvip_planar2is.vhd
set_module_property TOP_LEVEL_HDL_MODULE vbvip_planar2is
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME vbvip_planar2is
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file vbvip_planar2is.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DEFAULT_HSIZE NATURAL 800
set_parameter_property DEFAULT_HSIZE DEFAULT_VALUE 800
set_parameter_property DEFAULT_HSIZE DISPLAY_NAME DEFAULT_HSIZE
set_parameter_property DEFAULT_HSIZE TYPE NATURAL
set_parameter_property DEFAULT_HSIZE UNITS None
set_parameter_property DEFAULT_HSIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DEFAULT_HSIZE AFFECTS_GENERATION false
set_parameter_property DEFAULT_HSIZE HDL_PARAMETER true
add_parameter DEFAULT_VSIZE NATURAL 600
set_parameter_property DEFAULT_VSIZE DEFAULT_VALUE 600
set_parameter_property DEFAULT_VSIZE DISPLAY_NAME DEFAULT_VSIZE
set_parameter_property DEFAULT_VSIZE TYPE NATURAL
set_parameter_property DEFAULT_VSIZE UNITS None
set_parameter_property DEFAULT_VSIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DEFAULT_VSIZE AFFECTS_GENERATION false
set_parameter_property DEFAULT_VSIZE HDL_PARAMETER true
add_parameter DEFAULT_BPP NATURAL 24
set_parameter_property DEFAULT_BPP DEFAULT_VALUE 24
set_parameter_property DEFAULT_BPP DISPLAY_NAME DEFAULT_BPP
set_parameter_property DEFAULT_BPP TYPE NATURAL
set_parameter_property DEFAULT_BPP UNITS None
set_parameter_property DEFAULT_BPP ALLOWED_RANGES 0:2147483647
set_parameter_property DEFAULT_BPP AFFECTS_GENERATION false
set_parameter_property DEFAULT_BPP HDL_PARAMETER true
add_parameter DEFAULT_FIFO_DEPTH_POW2 NATURAL 10
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 DEFAULT_VALUE 10
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 DISPLAY_NAME DEFAULT_FIFO_DEPTH_POW2
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 TYPE NATURAL
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 UNITS None
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 ALLOWED_RANGES 0:2147483647
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 AFFECTS_GENERATION false
set_parameter_property DEFAULT_FIFO_DEPTH_POW2 HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point is_clk_rst
# | 
add_interface is_clk_rst clock end
set_interface_property is_clk_rst clockRate 0

set_interface_property is_clk_rst ENABLED true

add_interface_port is_clk_rst iIS_CLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point is_clk_rst_reset
# | 
add_interface is_clk_rst_reset reset end
set_interface_property is_clk_rst_reset associatedClock is_clk_rst
set_interface_property is_clk_rst_reset synchronousEdges DEASSERT

set_interface_property is_clk_rst_reset ENABLED true

add_interface_port is_clk_rst_reset iRST reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clocked_video
# | 
add_interface clocked_video conduit end

set_interface_property clocked_video ENABLED true

add_interface_port clocked_video iVID_CLK export Input 1
add_interface_port clocked_video iVID_DATA export Input default_bpp
add_interface_port clocked_video oOVERFLOW export Output 1
add_interface_port clocked_video iVID_DATAVALID export Input 1
add_interface_port clocked_video iVID_LOCKED export Input 1
add_interface_port clocked_video iVID_V_SYNC export Input 1
add_interface_port clocked_video iVID_H_SYNC export Input 1
add_interface_port clocked_video iVID_F export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dout
# | 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock is_clk_rst
set_interface_property dout associatedReset is_clk_rst_reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 1

set_interface_property dout ENABLED true

add_interface_port dout oIS_DATA data Output default_bpp
add_interface_port dout oIS_VALID valid Output 1
add_interface_port dout iIS_READY ready Input 1
add_interface_port dout oIS_SOP startofpacket Output 1
add_interface_port dout oIS_EOP endofpacket Output 1
# | 
# +-----------------------------------
