# TCL File Generated by Component Editor 11.1sp2
# Mon Jun 04 17:00:08 PDT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | vbvip_isdup "Video Stream Duplicator" v1.0
# | Wing-Chi Chow 2012.06.04.17:00:08
# | 
# | 
# | /nfs/home/wchow/project/vblox/ip/vbvip/vbvip_isdup.vhd
# | 
# |    ./vbvip_isdup.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module vbvip_isdup
# | 
set_module_property NAME vbvip_isdup
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Video and Image Processing/Component Library"
set_module_property AUTHOR "Wing-Chi Chow"
set_module_property DISPLAY_NAME "Video Stream Duplicator"
set_module_property TOP_LEVEL_HDL_FILE vbvip_isdup.vhd
set_module_property TOP_LEVEL_HDL_MODULE vbvip_isdup
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME vbvip_isdup
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file vbvip_isdup.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DEFAULT_DIN_HSIZE NATURAL 800
set_parameter_property DEFAULT_DIN_HSIZE DEFAULT_VALUE 800
set_parameter_property DEFAULT_DIN_HSIZE DISPLAY_NAME DEFAULT_DIN_HSIZE
set_parameter_property DEFAULT_DIN_HSIZE TYPE NATURAL
set_parameter_property DEFAULT_DIN_HSIZE UNITS None
set_parameter_property DEFAULT_DIN_HSIZE AFFECTS_GENERATION false
set_parameter_property DEFAULT_DIN_HSIZE HDL_PARAMETER true
add_parameter DEFAULT_DIN_VSIZE NATURAL 600
set_parameter_property DEFAULT_DIN_VSIZE DEFAULT_VALUE 600
set_parameter_property DEFAULT_DIN_VSIZE DISPLAY_NAME DEFAULT_DIN_VSIZE
set_parameter_property DEFAULT_DIN_VSIZE TYPE NATURAL
set_parameter_property DEFAULT_DIN_VSIZE UNITS None
set_parameter_property DEFAULT_DIN_VSIZE AFFECTS_GENERATION false
set_parameter_property DEFAULT_DIN_VSIZE HDL_PARAMETER true
add_parameter DEFAULT_BPP NATURAL 24
set_parameter_property DEFAULT_BPP DEFAULT_VALUE 24
set_parameter_property DEFAULT_BPP DISPLAY_NAME DEFAULT_BPP
set_parameter_property DEFAULT_BPP TYPE NATURAL
set_parameter_property DEFAULT_BPP UNITS None
set_parameter_property DEFAULT_BPP AFFECTS_GENERATION false
set_parameter_property DEFAULT_BPP HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset iRST reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point din0
# | 
add_interface din0 avalon_streaming end
set_interface_property din0 associatedClock clock
set_interface_property din0 associatedReset reset
set_interface_property din0 dataBitsPerSymbol 8
set_interface_property din0 errorDescriptor ""
set_interface_property din0 firstSymbolInHighOrderBits true
set_interface_property din0 maxChannel 0
set_interface_property din0 readyLatency 1

set_interface_property din0 ENABLED true

add_interface_port din0 oDIN_READY ready Output 1
add_interface_port din0 iDIN_VALID valid Input 1
add_interface_port din0 iDIN_DATA data Input default_bpp
add_interface_port din0 iDIN_SOP startofpacket Input 1
add_interface_port din0 iDIN_EOP endofpacket Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dout0
# | 
add_interface dout0 avalon_streaming start
set_interface_property dout0 associatedClock clock
set_interface_property dout0 associatedReset reset
set_interface_property dout0 dataBitsPerSymbol 8
set_interface_property dout0 errorDescriptor ""
set_interface_property dout0 firstSymbolInHighOrderBits true
set_interface_property dout0 maxChannel 0
set_interface_property dout0 readyLatency 1

set_interface_property dout0 ENABLED true

add_interface_port dout0 iDOUT0_READY ready Input 1
add_interface_port dout0 oDOUT0_VALID valid Output 1
add_interface_port dout0 oDOUT0_DATA data Output default_bpp
add_interface_port dout0 oDOUT0_SOP startofpacket Output 1
add_interface_port dout0 oDOUT0_EOP endofpacket Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dout1
# | 
add_interface dout1 avalon_streaming start
set_interface_property dout1 associatedClock clock
set_interface_property dout1 associatedReset reset
set_interface_property dout1 dataBitsPerSymbol 8
set_interface_property dout1 errorDescriptor ""
set_interface_property dout1 firstSymbolInHighOrderBits true
set_interface_property dout1 maxChannel 0
set_interface_property dout1 readyLatency 1

set_interface_property dout1 ENABLED true

add_interface_port dout1 iDOUT1_READY ready Input 1
add_interface_port dout1 oDOUT1_VALID valid Output 1
add_interface_port dout1 oDOUT1_DATA data Output default_bpp
add_interface_port dout1 oDOUT1_SOP startofpacket Output 1
add_interface_port dout1 oDOUT1_EOP endofpacket Output 1
# | 
# +-----------------------------------
