# TCL File Generated by Component Editor 10.1sp1
# Thu Aug 18 05:39:01 PDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | TERASIC_MULTI_TOUCH "TERASIC_MULTI_TOUCH" v1.0
# | null 2011.08.18.05:39:01
# | TERASIC_MULTI_TOUCH
# | 
# | D:/richard/touch/CD_SOPC/DE2_115_SOPC_MTL_PAINTER/ip/TERASIC_MULTI_TOUCH/TERASIC_MULTI_TOUCH.v
# | 
# |    ./TERASIC_MULTI_TOUCH.v syn, sim
# |    ./i2c_touch_config.v syn, sim
# |    ./touch_fifo.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module TERASIC_MULTI_TOUCH
# | 
set_module_property DESCRIPTION TERASIC_MULTI_TOUCH
set_module_property NAME TERASIC_MULTI_TOUCH
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc./DE2_115"
set_module_property DISPLAY_NAME TERASIC_MULTI_TOUCH
set_module_property TOP_LEVEL_HDL_FILE TERASIC_MULTI_TOUCH.v
set_module_property TOP_LEVEL_HDL_MODULE TERASIC_MULTI_TOUCH
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file TERASIC_MULTI_TOUCH.v {SYNTHESIS SIMULATION}
add_file i2c_touch_config.v {SYNTHESIS SIMULATION}
add_file touch_fifo.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave s_cs chipselect Input 1
add_interface_port avalon_slave s_address address Input 5
add_interface_port avalon_slave s_read read Input 1
add_interface_port avalon_slave s_readdata readdata Output 16
add_interface_port avalon_slave s_write write Input 1
add_interface_port avalon_slave s_writedata writedata Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end TOUCH_I2C_SDA export Bidir 1
add_interface_port conduit_end TOUCH_I2C_SCL export Output 1
add_interface_port conduit_end TOUCH_INT_n export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq_n irq_n Output 1
# | 
# +-----------------------------------
