
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2 (64-bit)
SW Build 928826 on Thu Jun  5 17:44:04 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Interrupt Handler Table for MicroBlaze Processor
*
*******************************************************************/

#include "microblaze_interrupts_i.h"
#include "xparameters.h"


extern void XNullHandler (void *);

/*
* The interrupt handler table for microblaze processor
*/

MB_InterruptVectorTableEntry MB_InterruptVectorTable[] =
{
{	XNullHandler,
	(void*) XNULL}
};

